
package g50.lrg.view;

import java.awt.Color;
import static g50.lrg.util.JDBCutil.playSound;


public class GUIInformes extends javax.swing.JFrame {

    public GUIInformes() {
        initComponents();
        setSize(750, 500);
        setLocationRelativeTo(null);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */

    //@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        informe1 = new javax.swing.JFrame();
        jPanel2 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        lblInf1 = new javax.swing.JLabel();
        defBoton1 = new javax.swing.JLabel();
        lblInf2 = new javax.swing.JLabel();
        defBoton = new javax.swing.JLabel();
        lblInf3 = new javax.swing.JLabel();
        defBoton2 = new javax.swing.JLabel();
        lblBannerMintic = new javax.swing.JLabel();
        lblTitulo = new javax.swing.JLabel();
        fondoPrincipal = new javax.swing.JLabel();

        jPanel2.setBackground(new java.awt.Color(204, 204, 255));

        jButton1.setText("jButton1");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(326, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(331, 331, 331))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(219, 219, 219)
                .addComponent(jButton1)
                .addContainerGap(258, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout informe1Layout = new javax.swing.GroupLayout(informe1.getContentPane());
        informe1.getContentPane().setLayout(informe1Layout);
        informe1Layout.setHorizontalGroup(
            informe1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(informe1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        informe1Layout.setVerticalGroup(
            informe1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Informes Base de Datos");
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblInf1.setFont(new java.awt.Font("Lucida Sans", 1, 11)); // NOI18N
        lblInf1.setForeground(new java.awt.Color(0, 51, 153));
        lblInf1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblInf1.setText("INFORME 1");
        lblInf1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblInf1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblInf1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblInf1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblInf1MouseExited(evt);
            }
        });
        jPanel1.add(lblInf1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 190, 90, 30));

        defBoton1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        defBoton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/g50/lrg/Recursos/btnazul2.png"))); // NOI18N
        jPanel1.add(defBoton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 190, 90, 30));

        lblInf2.setFont(new java.awt.Font("Lucida Sans", 1, 11)); // NOI18N
        lblInf2.setForeground(new java.awt.Color(0, 51, 153));
        lblInf2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblInf2.setText("INFORME 2");
        lblInf2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblInf2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblInf2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblInf2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblInf2MouseExited(evt);
            }
        });
        jPanel1.add(lblInf2, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 190, 90, 30));

        defBoton.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        defBoton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/g50/lrg/Recursos/btnazul2.png"))); // NOI18N
        jPanel1.add(defBoton, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 190, 90, 30));

        lblInf3.setFont(new java.awt.Font("Lucida Sans", 1, 11)); // NOI18N
        lblInf3.setForeground(new java.awt.Color(0, 51, 153));
        lblInf3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblInf3.setText("INFORME 3");
        lblInf3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblInf3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblInf3MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblInf3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblInf3MouseExited(evt);
            }
        });
        jPanel1.add(lblInf3, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 190, 90, 30));

        defBoton2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        defBoton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/g50/lrg/Recursos/btnazul2.png"))); // NOI18N
        jPanel1.add(defBoton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 190, 90, 30));

        lblBannerMintic.setForeground(new java.awt.Color(102, 255, 102));
        lblBannerMintic.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblBannerMintic.setIcon(new javax.swing.ImageIcon(getClass().getResource("/g50/lrg/Recursos/banne_ mintic03.png"))); // NOI18N
        lblBannerMintic.setMaximumSize(new java.awt.Dimension(500, 128));
        lblBannerMintic.setMinimumSize(new java.awt.Dimension(500, 128));
        lblBannerMintic.setName(""); // NOI18N
        lblBannerMintic.setPreferredSize(new java.awt.Dimension(500, 128));
        jPanel1.add(lblBannerMintic, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 310, 740, 130));

        lblTitulo.setFont(new java.awt.Font("Impact", 0, 24)); // NOI18N
        lblTitulo.setForeground(new java.awt.Color(0, 51, 153));
        lblTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitulo.setText("INFROMES BASE DE DATOS DE PROYECTOS DE CONSTRUCCION");
        jPanel1.add(lblTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(91, 51, 580, 58));

        fondoPrincipal.setForeground(new java.awt.Color(255, 255, 255));
        fondoPrincipal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/g50/lrg/Recursos/fondo.png"))); // NOI18N
        jPanel1.add(fondoPrincipal, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 750, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lblInf1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblInf1MouseClicked
        playSound("resources/click.wav");
        Informe1 inf1=new Informe1();
        inf1.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_lblInf1MouseClicked

    private void lblInf1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblInf1MouseEntered
        lblInf1.setForeground(new Color(0, 91, 255));
        lblInf1.setFont(new java.awt.Font("Lucida Sans", 3, 11));
    }//GEN-LAST:event_lblInf1MouseEntered

    private void lblInf1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblInf1MouseExited
        lblInf1.setForeground(new Color(0, 51, 153));
        lblInf1.setFont(new java.awt.Font("Lucida Sans", 1, 11));
    }//GEN-LAST:event_lblInf1MouseExited

    private void lblInf2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblInf2MouseClicked
        playSound("resources/click.wav");
        Informe2 inf2=new Informe2();
        inf2.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_lblInf2MouseClicked

    private void lblInf2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblInf2MouseEntered
        lblInf2.setForeground(new Color(0, 91, 255));
        lblInf2.setFont(new java.awt.Font("Lucida Sans", 3, 11));
    }//GEN-LAST:event_lblInf2MouseEntered

    private void lblInf2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblInf2MouseExited
        lblInf2.setForeground(new Color(0, 51, 153));
        lblInf2.setFont(new java.awt.Font("Lucida Sans", 1, 11));
    }//GEN-LAST:event_lblInf2MouseExited

    private void lblInf3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblInf3MouseClicked
        playSound("resources/click.wav");
        Informe3 inf3=new Informe3();
        inf3.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_lblInf3MouseClicked

    private void lblInf3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblInf3MouseEntered
        lblInf3.setForeground(new Color(0, 91, 255));
        lblInf3.setFont(new java.awt.Font("Lucida Sans", 3, 11));
    }//GEN-LAST:event_lblInf3MouseEntered

    private void lblInf3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblInf3MouseExited
        lblInf3.setForeground(new Color(0, 51, 153));
        lblInf3.setFont(new java.awt.Font("Lucida Sans", 1, 11));
    }//GEN-LAST:event_lblInf3MouseExited

    



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel defBoton;
    private javax.swing.JLabel defBoton1;
    private javax.swing.JLabel defBoton2;
    private javax.swing.JLabel fondoPrincipal;
    public javax.swing.JFrame informe1;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    public javax.swing.JLabel lblBannerMintic;
    private javax.swing.JLabel lblInf1;
    private javax.swing.JLabel lblInf2;
    private javax.swing.JLabel lblInf3;
    private javax.swing.JLabel lblTitulo;
    // End of variables declaration//GEN-END:variables
}
